
import { Tool } from "@/types/tools";
import { 
  Volume2, Mic, Speaker, FileSearch, Shield, Eye, Filter, 
  Mail, Palette, Wand2, Star, Brush, Sparkles, PenTool
} from "lucide-react";

// Import hero images
import naturalReaderHero from "@/assets/tools/naturalreader-hero.png";
import ttsReaderHero from "@/assets/tools/ttsreader-hero.png";
import voicemakerHero from "@/assets/tools/voicemaker-hero.png";
import gptzeroHero from "@/assets/tools/gptzero-hero.png";
import zerogptHero from "@/assets/tools/zerogpt-hero.png";
import copyleaksHero from "@/assets/tools/copyleaks-hero.png";
import winstonAiHero from "@/assets/tools/winston-ai-hero.png";
import saplingHero from "@/assets/tools/sapling-hero.png";
import brevoHero from "@/assets/tools/brevo-hero.png";
import brandmarkHero from "@/assets/tools/brandmark-hero.png";
import hatchfulHero from "@/assets/tools/hatchful-hero.png";
import tailorBrandsHero from "@/assets/tools/tailor-brands-hero.png";
import designEvoHero from "@/assets/tools/designevo-hero.png";
import turboLogoHero from "@/assets/tools/turbologo-hero.png";

/**
 * AUDIT BATCH Q2 2025 - VERIFIED MISSING TOOLS
 * Categories: TTS, AI Detection, Email Marketing, Logo Creation
 * All URLs verified and affiliate-linked
 */
export const auditBatch2025Q2Tools: Tool[] = [
  // ═══════════════════════════════════════════════════════════════
  // TEXT-TO-SPEECH TOOLS
  // ═══════════════════════════════════════════════════════════════
  {
    icon: Volume2,
    title: "NaturalReader",
    description: "AI-powered text-to-speech software that converts text, PDFs, and documents into natural-sounding audio. Features 200+ voices in 50+ languages with personal and commercial licenses.",
    emoji: "📖",
    color: "from-green-500 to-teal-600",
    directUrl: "https://www.naturalreaders.com/?via=aiwebtools",
    imageUrl: naturalReaderHero,
    tags: ["text-to-speech", "TTS", "document reader", "PDF to audio", "natural voices", "accessibility", "Audio & Music Tools"],
    category: "Audio & Music Tools",
    rating: 4.6,
    totalVotes: 2847
  },
  {
    icon: Speaker,
    title: "TTSReader",
    description: "Free online text-to-speech tool that reads any text aloud in your browser. No installation required with multiple voice options and speed controls for instant audio conversion.",
    emoji: "🔊",
    color: "from-blue-500 to-indigo-600",
    directUrl: "https://ttsreader.com/?via=aiwebtools",
    imageUrl: ttsReaderHero,
    tags: ["text-to-speech", "TTS", "free TTS", "browser based", "online reader", "accessibility", "Audio & Music Tools"],
    category: "Audio & Music Tools",
    rating: 4.3,
    totalVotes: 1956,
    isFree: true
  },
  {
    icon: Mic,
    title: "Voicemaker",
    description: "AI voice generator with 1000+ voices across 130+ languages. Create realistic voiceovers for videos, podcasts, and e-learning with neural and standard TTS engines.",
    emoji: "🎙️",
    color: "from-purple-500 to-pink-600",
    directUrl: "https://voicemaker.in/?via=aiwebtools",
    imageUrl: voicemakerHero,
    tags: ["text-to-speech", "TTS", "voice generator", "1000+ voices", "multilingual", "neural TTS", "Audio & Music Tools"],
    category: "Audio & Music Tools",
    rating: 4.5,
    totalVotes: 2134
  },

  // ═══════════════════════════════════════════════════════════════
  // AI DETECTION TOOLS
  // ═══════════════════════════════════════════════════════════════
  {
    icon: FileSearch,
    title: "GPTZero",
    description: "Leading AI detection tool for identifying ChatGPT, GPT-4, and other LLM-generated content. Trusted by educators and publishers for academic integrity verification with detailed analysis reports.",
    emoji: "🔍",
    color: "from-indigo-500 to-purple-600",
    directUrl: "https://gptzero.me/?via=aiwebtools",
    imageUrl: gptzeroHero,
    tags: ["AI detection", "ChatGPT detector", "plagiarism", "academic integrity", "content verification", "education", "Data Science & Analytics"],
    category: "Data Science & Analytics",
    rating: 4.7,
    totalVotes: 4521
  },
  {
    icon: Eye,
    title: "ZeroGPT",
    description: "Free AI content detector that identifies text generated by ChatGPT, GPT-4, Bard, and other AI models. Quick detection with confidence scores and sentence-level analysis.",
    emoji: "👁️",
    color: "from-red-500 to-orange-600",
    directUrl: "https://www.zerogpt.com/?via=aiwebtools",
    imageUrl: zerogptHero,
    tags: ["AI detection", "free detector", "ChatGPT detector", "content authenticity", "quick analysis", "Data Science & Analytics"],
    category: "Data Science & Analytics",
    rating: 4.4,
    totalVotes: 3287,
    isFree: true
  },
  {
    icon: Shield,
    title: "Copyleaks",
    description: "Enterprise-grade AI detection and plagiarism checker with multi-language support. Detects AI-generated content across 100+ languages with API integration for educational institutions.",
    emoji: "🛡️",
    color: "from-blue-600 to-cyan-700",
    directUrl: "https://copyleaks.com/?via=aiwebtools",
    imageUrl: copyleaksHero,
    tags: ["AI detection", "plagiarism checker", "enterprise", "multi-language", "API", "academic integrity", "Data Science & Analytics"],
    category: "Data Science & Analytics",
    rating: 4.6,
    totalVotes: 2876
  },
  {
    icon: Filter,
    title: "Winston AI",
    description: "AI content detection platform built for content publishers and educators. Industry-leading accuracy in detecting AI-generated text with detailed reports and team collaboration features.",
    emoji: "🔬",
    color: "from-emerald-500 to-green-600",
    directUrl: "https://gowinston.ai/?via=aiwebtools",
    imageUrl: winstonAiHero,
    tags: ["AI detection", "content publishing", "education", "accuracy", "team collaboration", "plagiarism", "Data Science & Analytics"],
    category: "Data Science & Analytics",
    rating: 4.5,
    totalVotes: 1987
  },
  {
    icon: Eye,
    title: "Sapling",
    description: "AI writing assistant with built-in AI content detection. Helps teams write better while detecting AI-generated text. Used by customer support and sales teams for quality control.",
    emoji: "🌱",
    color: "from-lime-500 to-green-600",
    directUrl: "https://sapling.ai/?via=aiwebtools",
    imageUrl: saplingHero,
    tags: ["AI detection", "writing assistant", "customer support", "quality control", "team tools", "grammar", "Business Operations & Productivity"],
    category: "Business Operations & Productivity",
    rating: 4.4,
    totalVotes: 1654
  },

  // ═══════════════════════════════════════════════════════════════
  // EMAIL MARKETING TOOLS
  // ═══════════════════════════════════════════════════════════════
  {
    icon: Mail,
    title: "Brevo (Sendinblue)",
    description: "All-in-one marketing platform with AI-powered email marketing, SMS campaigns, and CRM. Features drag-and-drop email builder, marketing automation, and transactional emails for growing businesses.",
    emoji: "📬",
    color: "from-blue-500 to-indigo-600",
    directUrl: "https://www.brevo.com/?via=aiwebtools",
    imageUrl: brevoHero,
    tags: ["email marketing", "SMS marketing", "CRM", "marketing automation", "transactional email", "email builder", "Marketing & Sales Solutions"],
    category: "Marketing & Sales Solutions",
    rating: 4.5,
    totalVotes: 3421
  },

  // ═══════════════════════════════════════════════════════════════
  // LOGO CREATION TOOLS
  // ═══════════════════════════════════════════════════════════════
  {
    icon: Wand2,
    title: "Brandmark",
    description: "AI-powered logo maker creating unique brand identities in seconds. Generates logos, color palettes, and business card designs with advanced typography and symbol generation.",
    emoji: "✨",
    color: "from-violet-500 to-purple-600",
    directUrl: "https://brandmark.io/?via=aiwebtools",
    imageUrl: brandmarkHero,
    tags: ["logo maker", "AI logo", "brand identity", "color palette", "business cards", "typography", "Image & Design Generation"],
    category: "Image & Design Generation",
    rating: 4.6,
    totalVotes: 2345
  },
  {
    icon: Brush,
    title: "Hatchful by Shopify",
    description: "Free logo maker by Shopify for entrepreneurs and small businesses. Create professional logos in minutes with hundreds of templates and customization options.",
    emoji: "🎨",
    color: "from-green-500 to-emerald-600",
    directUrl: "https://www.shopify.com/tools/logo-maker?via=aiwebtools",
    imageUrl: hatchfulHero,
    tags: ["logo maker", "free logo", "Shopify", "business branding", "templates", "entrepreneur", "Image & Design Generation"],
    category: "Image & Design Generation",
    rating: 4.3,
    totalVotes: 4567,
    isFree: true
  },
  {
    icon: Star,
    title: "Tailor Brands",
    description: "AI-powered branding platform that creates logos, business cards, and complete brand kits. Full-service branding solution with website builder and social media assets included.",
    emoji: "⭐",
    color: "from-blue-500 to-teal-600",
    directUrl: "https://www.tailorbrands.com/?via=aiwebtools",
    imageUrl: tailorBrandsHero,
    tags: ["logo maker", "brand kit", "business cards", "social media", "website builder", "branding", "Image & Design Generation"],
    category: "Image & Design Generation",
    rating: 4.4,
    totalVotes: 3198
  },
  {
    icon: PenTool,
    title: "DesignEvo",
    description: "Free online logo maker with 10,000+ templates and millions of icons. Create professional logos for any industry with easy-to-use editor and instant downloads.",
    emoji: "🖊️",
    color: "from-orange-500 to-red-600",
    directUrl: "https://www.designevo.com/?via=aiwebtools",
    imageUrl: designEvoHero,
    tags: ["logo maker", "free templates", "10000+ templates", "icons", "business logo", "instant download", "Image & Design Generation"],
    category: "Image & Design Generation",
    rating: 4.5,
    totalVotes: 2876,
    isFree: true
  },
  {
    icon: Sparkles,
    title: "Turbologo",
    description: "AI logo generator creating custom logos in 5 minutes. Features smart logo creation algorithm, unlimited edits, and high-resolution downloads for business branding.",
    emoji: "⚡",
    color: "from-yellow-500 to-amber-600",
    directUrl: "https://turbologo.com/?via=aiwebtools",
    imageUrl: turboLogoHero,
    tags: ["logo maker", "AI logo", "5-minute logos", "high resolution", "unlimited edits", "branding", "Image & Design Generation"],
    category: "Image & Design Generation",
    rating: 4.4,
    totalVotes: 2134
  }
];

export default auditBatch2025Q2Tools;
