
import { Tool } from "@/types/tools";
import { 
  FileText, PenTool, Wand2, Bot, Video, Film, Sparkles,
  Search, Brain, Cpu, Zap
} from "lucide-react";

// Hero image imports
import smodinHero from "@/assets/tools/smodin-hero.png";
import hyperwriteHero from "@/assets/tools/hyperwrite-hero.png";
import jennyAiHero from "@/assets/tools/jenny-ai-hero.png";
import humanOrAiHero from "@/assets/tools/human-or-ai-hero.png";
import nvidiaCosmosHero from "@/assets/tools/nvidia-cosmos-hero.png";
import kling26Hero from "@/assets/tools/kling-26-hero.png";
import ltx2Hero from "@/assets/tools/ltx2-hero.png";

// Audit Batch Q2 2025 Part 8: Finance, Text Generators, Research & Science, Text-to-Video
export const auditBatch2025Q2Part8Tools: Tool[] = [
  // TEXT GENERATORS
  {
    icon: PenTool,
    title: "Smodin",
    description: "AI-powered writing platform featuring rewriter, plagiarism checker, text generator, and multilingual tools. Write essays, research papers, and content in 100+ languages with AI assistance.",
    emoji: "✍️",
    color: "from-green-500 to-teal-600",
    directUrl: "https://smodin.io/?via=aiwebtools",
    imageUrl: smodinHero,
    tags: ["AI Writer", "Rewriter", "Plagiarism Checker", "Essay Writer", "Multilingual", "Research Papers", "Content Generator"],
    category: "Writing & Content Enhancement",
    rating: 4.6,
    totalVotes: 4567
  },
  {
    icon: Wand2,
    title: "HyperWrite AI",
    description: "Personal AI writing assistant that learns your style and helps you write faster. Features AutoWrite, TypeAhead suggestions, and an AI agent that can browse the web and complete tasks.",
    emoji: "⚡",
    color: "from-purple-500 to-pink-600",
    directUrl: "https://www.hyperwriteai.com/?via=aiwebtools",
    imageUrl: hyperwriteHero,
    tags: ["AI Writer", "Personal Assistant", "AutoWrite", "Writing Style", "Browser Agent", "Content Creation"],
    category: "Writing & Content Enhancement",
    rating: 4.5,
    totalVotes: 3890
  },
  {
    icon: FileText,
    title: "Jenny AI",
    description: "AI research and writing assistant designed for academics and professionals. Summarize papers, generate citations, and write research documents with intelligent AI support.",
    emoji: "📝",
    color: "from-blue-500 to-indigo-600",
    directUrl: "https://jenni.ai/?via=aiwebtools",
    imageUrl: jennyAiHero,
    tags: ["Academic Writing", "Research Assistant", "Citations", "Summarizer", "Essay Writing", "Paper Writer"],
    category: "Writing & Content Enhancement",
    rating: 4.7,
    totalVotes: 5123
  },

  // RESEARCH & SCIENCE
  {
    icon: Search,
    title: "Human or AI",
    description: "Advanced AI content detection tool that identifies whether text was written by humans or generated by AI like ChatGPT, Claude, or other language models. Essential for educators and publishers.",
    emoji: "🔍",
    color: "from-orange-500 to-red-600",
    directUrl: "https://www.humanornot.ai/?via=aiwebtools",
    imageUrl: humanOrAiHero,
    tags: ["AI Detection", "Content Verification", "Plagiarism", "ChatGPT Detector", "Academic Integrity", "AI Checker"],
    category: "Research & Academic",
    rating: 4.4,
    totalVotes: 3456
  },
  {
    icon: Cpu,
    title: "NVIDIA Cosmos",
    description: "NVIDIA's world foundation model platform for physical AI development. Advanced AI models understanding the physical world for robotics, autonomous vehicles, and simulation.",
    emoji: "🌌",
    color: "from-green-500 to-emerald-600",
    directUrl: "https://www.nvidia.com/en-us/ai/cosmos/?via=aiwebtools",
    imageUrl: nvidiaCosmosHero,
    tags: ["NVIDIA", "Foundation Model", "Physical AI", "Robotics", "Autonomous Vehicles", "Simulation", "World Model"],
    category: "Research & Academic",
    rating: 4.8,
    totalVotes: 4890
  },

  // TEXT-TO-VIDEO
  {
    icon: Video,
    title: "Kling 2.6",
    description: "Kuaishou's latest Kling AI video generation model with enhanced quality, longer duration support, and improved motion coherence. Create stunning cinematic videos from text prompts.",
    emoji: "🎬",
    color: "from-blue-500 to-purple-600",
    directUrl: "https://klingai.com/?via=aiwebtools",
    imageUrl: kling26Hero,
    tags: ["Kling", "Text-to-Video", "Video Generator", "AI Video", "Kuaishou", "Cinematic", "Motion"],
    category: "Video Generation",
    rating: 4.8,
    totalVotes: 6789
  },
  {
    icon: Film,
    title: "LTX-2",
    description: "Lightricks' next-generation video AI model for high-quality text-to-video and image-to-video generation. Create professional videos with realistic motion and cinematic quality.",
    emoji: "🎥",
    color: "from-cyan-500 to-blue-600",
    directUrl: "https://ltx.studio/?via=aiwebtools",
    imageUrl: ltx2Hero,
    tags: ["Lightricks", "LTX", "Text-to-Video", "Video Generator", "AI Video", "Image-to-Video", "Professional"],
    category: "Video Generation",
    rating: 4.7,
    totalVotes: 4234
  }
];
